### ISSUE TITLE
Issue with null Safety

### ISSUE THREAD

**Issue by RileyManda** [hosain-mohamed/curved_splash_screen#1]
I am experiencing a null safety issue with your library in Android Studio
**The library 'package:curved_splash_screen/curved_splash_screen.dart' is legacy, and should not be imported into a null safe library.**

**Comment by hosain-mohamed** [comment]
Hi Riley,
Yes, the package is still not upgraded to Null-Safety version.
will try to implement it in the near future.

Thanks

**Comment by RileyManda** [comment]
> Hi Riley, Yes, the package is still not upgraded to Null-Safety version. will try to implement it in the near future.
> 
> Thanks

Thanks @hosain-mohamed 
My work around was adding `//@dart=2.9` to my main.dart.
<img width="770" alt="Screen Shot 2021-10-12 at 5 58 16 PM" src="https://user-images.githubusercontent.com/37291194/136990009-eac5d6fe-fe3c-46a4-b486-319b520d95c2.png">

**Comment by Riswanrio** [comment]
when i pressed skip the skip button is not responsive
